//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseno_Desarrollo_Grupo5.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOS
    {
        public int ID_PAGO { get; set; }
        public int ID_VENTA { get; set; }
        public decimal MONTO { get; set; }
        public string METODO { get; set; }
        public string REFERENCIA { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual VENTAS VENTAS { get; set; }
    }
}
